name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
          mkdocs-material \
          mkdocs-awesome-pages-plugin \
      - name: Install git-revision-date
        run: |
          pip install pyflakes
          pyflakes mkdocs-git-revision-date-localized-plugin
      - name: Deployement
        run: mkdocs gh-deploy --force
